spring:
  data:
    mongodb:
      database: ratings
      host: mongo
      port: 27017

---

spring:
  profiles: insight
  data:
    mongodb:
      database: insights
server:
  port: 8081
